<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Random_Shuffler</text>

        <Action name="shuffle_action">
        <icon></icon>
        <text>shuffle!</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>7</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
		
		<Action name="area_shuffle_action">
        <icon></icon>
        <text>area_shuffle!</text>
        <whatsThis></whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>0</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut>8</shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
		
		
    </Actions>
</ActionCollection>